### ISSUE TITLE
Fix particDesc

### ISSUE THREAD

**Issue by cmil** [dracor-org/romdracor#1]
In several plays there seem to have been mistakes when generating the `<listPerson>` of the `<particDesc>`.

E.g. in [seneca-hercules-furens.xml](https://github.com/dracor-org/romandracor/blob/816c278c535280579e9f005b2e2c50591dad6320/tei/seneca-hercules-furens.xml) the entry 

```xml
<person xml:id="hercvlestheseusamphitryonmegara">
  <persName>Hercvles Theseus Amphitryon Megara</persName>
</person>
```

needs to be split into separate entries for Theseus, Amphytrion and Megara (an entry for Hercules already exists).

In [terence-phormio.xml](https://github.com/dracor-org/romandracor/blob/816c278c535280579e9f005b2e2c50591dad6320/tei/terence-phormio.xml) none of the entries corresponds to actual characters.

```xml
<listPerson>
	<person xml:id="ph">
		<persName>Ph</persName>
	</person>
	<person xml:id="prologus">
		<persName>Prologus</persName>
	</person>
</listPerson>
```

For more transparency and easier correcting of mistakes can we maybe add the scripts used to generate the DraCor markup to the repo?

**Comment by nevmenandr** [comment]
I don't think that tp put this script online is a good idea. The code was written for one time run it is not reusable and it full of non optimal solutions. 

I think I can correct all these mistakes.

**Comment by nevmenandr** [comment]
I've fixed most of the issues, but I'm not sure if it is done for all f them because of the poor source enoding (typos, inconsistent markup and so on)

**Comment by lehkost** [comment]
This example is a monologue by Medea (not a speech by the two characters mentioned). So I guess "Medea Nvtrix" should be wrapped as ```<stage>``` and then ```<sp who="#medea">```.

Since this is unclear from the text and markup itself, I think we have to manually check passages like this.
