### ISSUE TITLE
Harmonize xml:lang-Attributes

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/romdracor#4]
@lehkost, have we agreed, which values should be used to indicate the language of a play/a title/... the conventions vary across corpora, e.g. this corpus uses `latin`, `ru`, `en`; according to ISO-639-1, https://de.wikipedia.org/wiki/Liste_der_ISO-639-1-Codes

**Comment by nevmenandr** [comment]
done for romdracor and greekdracor

**Comment by lehkost** [comment]
Thanks, we decided to follow 639-2/B, which is the case for Rom~ and Greek~.
