### ISSUE TITLE
use http:// in namespace of wikidata-URIs only

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/romdracor#5]
WIkidata use `http://` in it's URIs, e.g. Zeus (Q34201):

Website: https://www.wikidata.org/wiki/Q34201
http://www.wikidata.org/wiki/Q34201 redirects to https://www.wikidata.org/wiki/Q34201

But in the RDF (which is relevant for our Linked Data-Implementation) wikidata uses `http://` as it's namespace:

```
<rdf:Description rdf:about="http://www.wikidata.org/entity/Q34201">
    <rdf:type rdf:resource="http://wikiba.se/ontology#Item"/>
</rdf:Description>
<!.-- ... -->
```
see: 
`curl -o Q34201.rdf -L -H "Accept: application/rdf+xml" http://www.wikidata.org/entity/Q34201`

@lehkost, this should apply to all corpora.

**Comment by nevmenandr** [comment]
done for greekdracor and romdracor.
NB: https was used in header also, not only in `ana` attribute
